[package]
name = "rust_authenticator"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
jsonwebtoken = "9.3.1"
